package learn.er_modelling.entity.exercise_1;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Embeddable;
import java.io.Serializable;

/**
 * <a href="https://stackoverflow.com/a/5127262/10582056">https://stackoverflow.com/a/5127262/10582056</a>
 * <p>
 * with JPA, in order to have the chance to have extra columns, you need to use two OneToMany associations,
 * instead of a single ManyToMany relationship. You can also add a column with autogenerated values; this way,
 * it can work as the primary key of the table, if useful.
 */
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Embeddable
class PlayedId implements Serializable {

    private Integer playerId;

    private Integer matchId;
}
